name: Node.js Jest Testing

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

env:
  NEXT_PUBLIC_BASE_URL: https://example.com
  NEXT_PUBLIC_POSTHOG_HOST: https://eu.i.posthog.com
  NEXT_PUBLIC_POSTHOG_KEY: somekeyidk


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
